# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master

# Build Agent
pool:
  name: Azure Pipelines
  vmImage: "ubuntu-16.04"

# Build Format
name: 0.0.0.$(rev:.r)

# Variables
variables:

# Build Steps
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - task: Bash@3
    displayName: "Install TFX-CLI"
    inputs:
      targetType: "inline"
      script: |
        sudo npm install -g core-js@3
        sudo npm install -g tfx-cli

  - task: PowerShell@2
    displayName: "Build Azure DevOps Extension"
    inputs:
      targetType: filePath
      filePath: ./build-publish.ps1
      failOnStdErr: false
      workingDirectory: ./

  - task: CopyFiles@2
    displayName: "Copy Azure DevOps Extension to $(Build.ArtifactStagingDirectory)"
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      Contents: |
        **/build-publish.ps1
        **/*.vsix
        !**.git/**
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
